/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c9b13583-23fd-4fee-bcfa-8a666339cbb7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7QuIjne5u",
    "aws_user_pools_web_client_id": "6r585oockn2he4tg58e9laitia",
    "oauth": {}
};


export default awsmobile;
